// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqwzPmF0MqcvGXj-6Z0jTjbuxk2uqF9Sk',
    appId: '1:489104179920:web:a7251cb801d03a9601d4d5',
    messagingSenderId: '489104179920',
    projectId: 'radreports-b6f17',
    authDomain: 'radreports-b6f17.firebaseapp.com',
    storageBucket: 'radreports-b6f17.appspot.com',
    measurementId: 'G-E2XQ8YR5YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM62YbdGUKWviQGQyb9Oaf11h3QZQR0xM',
    appId: '1:489104179920:android:8a1c98e2175eb4da01d4d5',
    messagingSenderId: '489104179920',
    projectId: 'radreports-b6f17',
    storageBucket: 'radreports-b6f17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrR0FQxUDxZBXsN6FePVL_rgmVDLLh7D4',
    appId: '1:489104179920:ios:f12b3c200f8a933f01d4d5',
    messagingSenderId: '489104179920',
    projectId: 'radreports-b6f17',
    storageBucket: 'radreports-b6f17.appspot.com',
    iosBundleId: 'com.aeologic.restApiFlutter',
  );
}
